# Generated by Django 3.2.7 on 2023-03-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='image',
        ),
    ]
