# Generated by Django 4.1.6 on 2023-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kindofmovie_rename_title_movie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Keanu Reeves', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default='1h35m', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='when',
            field=models.IntegerField(default=2023),
        ),
    ]
