# Generated by Django 4.1.6 on 2023-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_cast_movie_length_movie_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='kind',
        ),
        migrations.DeleteModel(
            name='KindOfMovie',
        ),
        migrations.AddField(
            model_name='movie',
            name='kind',
            field=models.CharField(default='', max_length=255),
        ),
    ]
