# Generated by Django 4.1.6 on 2023-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_kind_delete_kindofmovie_movie_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ManyToManyField(to='core.video'),
        ),
    ]
